### ISSUE TITLE
Reorder js execution to avoid visual flash of username

### ISSUE THREAD

**Issue by stupiddingo** [idahofishgame/style#4]
To avoid flash of username perhaps we refactor this a bit:
1. Get username from json and update utilities section in upper right
2. Two go and retrieve main menu and load
3. Update username in main menu to match step 1
4. Somewhere along we have to add returnurl to the to accounts links also.  This could happen at the end or inline, but we'll have to add to the main menu part after insertion at step 2.

@floydnoel do you mind taking a whack at this since you're working with this code right now?

**Comment by floydnoel** [comment]
PR #6 login animation should end username flickering.
