### ISSUE TITLE
Needs "X-UA-Compatible" meta tag?

### ISSUE THREAD

**Issue by idahoboy** [idahofishgame/style#7]
<meta http-equiv="X-UA-Compatible" content="IE=edge"> 

This tag associated with Bootstrap should fix the issues where a browser defaults to compatibility mode.

This will save us many hours of pain trouble-shooting IDFG configurations in IE.

**Comment by stupiddingo** [comment]
Could have sworn we already had this, but no.

**Comment by idahoboy** [comment]
I thought we did too.

**Comment by stupiddingo** [comment]
Does it still have to be the first meta tag?

**Comment by stupiddingo** [comment]
Added some while back.
